### ISSUE TITLE
Could you give any instruction about how to run the code?

### ISSUE THREAD

**Issue by lz321cc321** [HybridRobotics/Lane-Change-CBF#1]
hello,Suiyi He.
Can you tell me how can I achieve the results in the article Fig.5 and Fig.7 and youtube results?
I followed the README.md and did not realize completely.
I I only achieved the first result in the article Fig.5. Is it a problem with the matlab version?,I use 2021a .
Best regards:
Tao Zhao

**Comment by junzengx14** [comment]
Just noticed this issue, copied this to Suiyi!

**Comment by hesuieins** [comment]
Hi, I think I have sent email to Tao regarding to this issue.

**Comment by lz321cc321** [comment]
thank you very much for your help！
